eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: ${eureka_url:http://192.168.0.22:8761/eureka}
    instance:
        preferIpAddress: true
        hostname: 192.168.0.22
server:
    port: 8082
spring:
    application:
        name: DEPARTMENT-SERVICE
    cloud:
        inetutils:
            preferredNetworks:
                - 192.168