

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${eureka_url:http://192.168.0.22:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: 192.168.0.22
server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forward:/departmentServiceFallBack


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000



management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
